### ISSUE TITLE
Gmaps support

### ISSUE THREAD

**Issue by mikokch** [83tb/rethink-lms#1]
Mapy Google możemy zintegrować, ale "nie bezpośrednio" (jak rozumiem).
Google ToS w zasadzie na to nie pozwalają. Również w naszej aplikacji oficjalnie byłby problem.
ref: https://github.com/openlayers/ol3/issues/2205

Wolę używać np. Mapboxa (https://www.mapbox.com/)

Gmapy mogę spróbować zintegrować ew. ma próbę...

**Comment by 83tb** [comment]
nie, luz, jak to problem to nie

**Comment by mikokch** [comment]
problem z "zasadami użytkowania". Technicznie to do wykonania:
http://openlayers.org/en/v3.0.0/examples/google-map.html
Choć w zasadzie są to dwie różne mapy zsynchronizowane i nałożone na siebie.
Ok, olewamy. (może później rzucę na to okiem w celach "demo")
