### ISSUE TITLE
tornado-angular conflict

### ISSUE THREAD

**Issue by mikokch** [83tb/rethink-lms#3]
wygląda że expressions od angulara w template kłócą się jakoś z tornado, chyba próbuje interpretować zawartość index.html

**Comment by mikokch** [comment]
temp solution:
http://stackoverflow.com/a/29293126

**Comment by 83tb** [comment]
a czemu nie mozesz tak:
angular.module('myApp', []).config(function($interpolateProvider){ $interpolateProvider.startSymbol('{[{').endSymbol('}]}'); });

**Comment by mikokch** [comment]
bo... nie wiedziałem, że mogę ;)
